# -*- coding: utf-8 -*-
"""한화투자증권 뉴스 크롤링 봇 깃용 ver1.1_260403

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EdRMk6Y7Z1VDcV7vRz1K5TIzmK4F6CmJ
"""

#============================================
# Import library
#============================================
import feedparser
import requests
from newspaper import Article
from difflib import SequenceMatcher
import smtplib
import os

EMAIL_SENDER = os.getenv("EMAIL_SENDER")
EMAIL_PASSWORD = os.getenv("EMAIL_PASSWORD")
from email.mime.text import MIMEText
from urllib.parse import urlparse, parse_qs # parse_qs 추가
from bs4 import BeautifulSoup # Added for web scraping
# from lxml_html_clean import Cleaner # lxml_html_clean은 현재 사용하지 않으므로 주석 처리

#============================================
# Setting crawling(SMTP)
#============================================
KEYWORDS=[
"핀테크",
"금융 AI",
"AI 금융",
"금융 데이터",
"디지털 금융",
"generative AI fintech",
"AI banking",
"블록체인",
"blockchain",
"STO",
"RWA",
"조각투자",
"스테이블",
"CBDC"
]

# NAVER_CLIENT_ID="YOUR_NAVER_CLIENT_ID" #  Naver Client ID 입력
# NAVER_CLIENT_SECRET="YOUR_NAVER_CLIENT_SECRET" # Naver Client Secret 입력


EMAIL_SENDER="delusion1083@gmail.com"
EMAIL_PASSWORD="ikpj tncz fpjb cydr"
EMAIL_RECEIVER=[
"202503129@hanwha.com",
#"js0408@hanwha.com",
#"heesun.kim@hanwha.com",
#"202001558@hanwha.com",
#"201905270@hanwha.com"
]

def get_google_news():

    articles=[]

    for keyword in KEYWORDS:

        encoded_keyword = requests.utils.quote(keyword)
        url=f"https://news.google.com/rss/search?q={encoded_keyword}&hl=ko&gl=KR&ceid=KR:ko"

        feed=feedparser.parse(url)

        for entry in feed.entries:

            # publication date
            pub_date = getattr(entry, 'published', 'N/A')

            # Google News redirect → 실제 기사 URL
            # resolve_google_news_url 함수는 get_article 함수에서 처리하도록 변경되었으므로 직접 사용 X
            # entry.link가 Google News 링크이므로, 이걸 직접 get_article로 넘김
            google_link = entry.link
            # real_link = resolve_google_news_url(google_link) # 이 라인이 오류를 발생시켰으므로 제거

            articles.append({
                "title": entry.title,
                "link": google_link, # 실제 기사 링크는 get_article에서 최종적으로 처리
                "source": "Google",
                "published_date": pub_date
            })

    return articles

#============================================
# del duplication 1: subject similarity
#============================================
def similar(a,b):
    return SequenceMatcher(None,a,b).ratio()

#============================================
# del duplication 2: filtering Domain
#============================================
def remove_domain_duplicates(news):

    seen_domains=set()
    filtered=[]

    for n in news:

        domain=urlparse(n["link"]).netloc

        if domain not in seen_domains:

            filtered.append(n)
            seen_domains.add(domain)

    return filtered

#============================================
# del duplication 3: del duplicates, integration
#============================================

def remove_duplicates(news):

    seen_urls = set()
    filtered = []

    for n in news:

        # URL 중복 제거
        if n["link"] in seen_urls:
            continue

        # 제목 유사도 제거
        duplicate = False
        for f in filtered:
            if similar(n["title"], f["title"]) > 0.85:
                duplicate = True
                break

        if not duplicate:
            filtered.append(n)
            seen_urls.add(n["link"])

    return filtered

    # Removed remove_domain_duplicates as it was overly aggressive with Google News links
    # If domain-based filtering is desired, it should be applied to the final resolved URLs
    # filtered=remove_domain_duplicates(filtered)

    return filtered

import requests
import re
from newspaper import Article
from bs4 import BeautifulSoup
from urllib.parse import urlparse, parse_qs
from googlenewsdecoder import new_decoderv1  # 신규 라이브러리 추가

#============================================
# Google News URL → 실제 기사 URL 복호화
#============================================
def decode_google_news_url(url):
    """
    googlenewsdecoder 라이브러리를 사용하여 Google News RSS URL을
    실제 기사 URL로 변환합니다. 기존 수동 base64 디코딩을 대체합니다.
    """
    try:
        result = new_decoderv1(url)
        if result.get("status") and result.get("decoded_url"):
            print(f"DEBUG_DECODE: 성공 → {result['decoded_url']}")
            return result["decoded_url"]
    except Exception as e:
        print(f"ERROR_DECODE: googlenewsdecoder 실패 → {e}")
    return None


#============================================
# 기사 본문 크롤링(URL 해소 + Newspaper3k + BeautifulSoup fallback)
#============================================
def get_article(url, session=None):
    article_text = ""
    requester = session if session else requests

    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
    }

    print(f"DEBUG: get_article 시작 → {url}")

    # Step 1: Google News RSS CBM URL이면 googlenewsdecoder로 복호화
    final_article_url = url
    if "news.google.com" in url:
        decoded = decode_google_news_url(url)
        if decoded:
            final_article_url = decoded
            print(f"DEBUG: 복호화 성공 → {final_article_url}")
        else:
            # Step 2: 복호화 실패 시 requests로 직접 follow redirect
            print("DEBUG: 복호화 실패, requests redirect 시도")
            try:
                resp = requester.get(url, allow_redirects=True, timeout=5, headers=headers)
                effective = resp.url
                if "news.google.com" not in effective:
                    final_article_url = effective
                    print(f"DEBUG: redirect 최종 URL → {final_article_url}")
            except Exception as e:
                print(f"ERROR: redirect 실패 → {e}")
                return ""

    # Step 3: Newspaper3k로 본문 추출
    print(f"DEBUG: 최종 기사 URL → {final_article_url}")
    try:
        article = Article(final_article_url)
        article.download()
        article.parse()
        article_text = article.text
        print(f"DEBUG: Newspaper3k 추출 길이 → {len(article_text)}")
    except Exception as e:
        print(f"DEBUG: Newspaper3k 실패 → {e}")
        article_text = ""

    # Step 4: Newspaper3k 실패 시 BeautifulSoup fallback
    if not article_text.strip() or len(article_text.strip()) < 100:
        print(f"DEBUG: BeautifulSoup fallback 시작 → {final_article_url}")
        try:
            fb_resp = requester.get(final_article_url, allow_redirects=True, timeout=5, headers=headers)
            fb_resp.raise_for_status()
            soup = BeautifulSoup(fb_resp.text, 'html.parser')

            for tag in soup(['script', 'style', 'header', 'footer', 'nav', 'aside', 'form', 'iframe', 'noscript']):
                tag.decompose()

            # 국내 주요 언론사 CSS 클래스명 추가 보완
            CONTENT_CLASSES = [
                # 국내 언론사
                'article-body', 'article_body', 'article_content', 'articleCont',
                'article-view-body', 'view_con', 'view_content', 'news_content',
                'news_contents', 'newsct_article', 'dic_area',  # 네이버 뉴스
                'articleBodyContents',  # 조선비즈 등
                'article-text', 'article__body', 'text_area', 'cnt_text',
                'story_content', 'cont_article', 'article_txt',
                # 해외 언론사
                'entry-content', 'post-content', 'main-content', 'story-body',
            ]

            paragraphs = []
            main_area = soup.find('article') or soup.find('main')

            if not main_area:
                for cls in CONTENT_CLASSES:
                    main_area = soup.find(class_=cls)
                    if main_area: break

            target = main_area if main_area else soup
            for p in target.find_all('p'):
                txt = p.get_text(separator=' ', strip=True)
                if len(txt) > 40:
                    paragraphs.append(txt)

            article_text = '\n\n'.join(paragraphs)
            print(f"DEBUG: BeautifulSoup 추출 길이 → {len(article_text)}")

        except Exception as e:
            print(f"ERROR: BeautifulSoup fallback 실패 → {e}")
            article_text = ""

    print(f"DEBUG: 최종 본문 길이 → {len(article_text)}")
    return article_text[:3000]

#============================================
# Collect data(naver news) - REMOVED AS PER USER REQUEST
#============================================
# def get_naver_news():

#     articles=[]

#     for keyword in KEYWORDS:

#         encText = requests.utils.quote(keyword)
#         url = f"https://openapi.naver.com/v1/search/news.json?query={encText}&display=100&start=1&sort=date"
#         headers = {
#             "X-Naver-Client-Id": NAVER_CLIENT_ID,
#             "X-Naver-Client-Secret": NAVER_CLIENT_SECRET
#         }
#         response = requests.get(url, headers=headers)

#         if response.status_code == 200:
#             json_data = response.json()
#             for item in json_data.get("items", []):
#                 articles.append({
#                     "title": item["title"].replace("&quot;", "\"").replace("<b>", "").replace("</b>", ""),
#                     "link": item["link"],
#                     "source": "Naver"
#                 })
#         else:
#             print(f"Error fetching Naver news for {keyword}: {response.status_code}")

#     return articles

# =========================================
# 라이브러리
# =========================================

import matplotlib.pyplot as plt
from collections import Counter

# =========================================
# 뉴스 태그 분류
# =========================================

def classify_tag(text):

    text=text.lower()

    ai_keywords=[
        "ai","인공지능","생성형","gpt","llm","머신러닝","딥러닝"
    ]

    fintech_keywords=[
        "핀테크","fintech","결제","payment","가상자산",
        "블록체인","디지털 금융"
    ]

    for k in ai_keywords:
        if k in text:
            return "AI"

    for k in fintech_keywords:
        if k in text:
            return "Fintech"

    return "Digital"


# =========================================
# 뉴스 중요도 계산
# =========================================

def calculate_importance(news):

    important_keywords=[
        "ai","인공지능","핀테크","fintech",
        "투자","규제","플랫폼","생성형","증권"
    ]

    big_companies=[
        "삼성","네이버","카카오","신한투자","한국투자","하나투자",
        "google","microsoft","amazon",
        "tesla","openai"
    ]

    text=(news["title"]+" "+news.get("summary","")).lower()

    score=0

    for k in important_keywords:
        if k in text:
            score+=2

    for c in big_companies:
        if c.lower() in text:
            score+=3

    return score


# =========================================
# 뉴스 분석(태그 + 중요도)
# =========================================

def enrich_news(news):

    for n in news:

        text=n["title"]+" "+n.get("summary","")

        n["tag"]=classify_tag(text)

        n["importance"]=calculate_importance(n)

    news=sorted(news,key=lambda x:x["importance"],reverse=True)

    return news


# =========================================
# 뉴스 트렌드 분석 그래프
# =========================================

def generate_trend_chart(news):

    tags=[n["tag"] for n in news]

    counter=Counter(tags)

    labels=list(counter.keys())
    values=list(counter.values())

    plt.figure()

    plt.bar(labels,values)

    plt.title("News Trend Analysis")
    plt.xlabel("Category")
    plt.ylabel("News Count")

    file_name="news_trend_chart.png"

    plt.savefig(file_name)

    plt.close()

    return file_name


# =========================================
# PDF 리포트 생성
# =========================================

# generate_weekly_pdf 함수 삭제


# =========================================
# 이메일 내용 생성
# =========================================

def create_email_content(news):

    body="디지털L&D센터 NewsLetter Briefing\n\n"

    body+="[주요 뉴스 TOP20]\n\n"

    for n in news[:20]:

        body+=f"""
[{n['tag']}] {n['title']}
요약: {n.get('summary', '요약 없음')}
출처: {n['source']}
중요도: {n['importance']}
링크: {n['link']}

"""

    return body

#============================================
# summarization(sumy 추출 요약 - 로컬)
# 모델 다운로드 없이 텍스트에서 핵심 문장을 추출하는 방식으로
#============================================
from sumy.parsers.plaintext import PlaintextParser
from sumy.nlp.tokenizers import Tokenizer
from sumy.summarizers.lex_rank import LexRankSummarizer
from sumy.summarizers.lsa import LsaSummarizer
from langdetect import detect, LangDetectException
import nltk
nltk.download('punkt', quiet=True)
nltk.download('punkt_tab', quiet=True)

def detect_language(text):
    try:
        lang = detect(text[:500])
        print(f"DEBUG: 감지 언어 → {lang}")
        return lang
    except LangDetectException:
        print("DEBUG: 언어 감지 실패, 기본값 'korean' 사용")
        return "ko"

def summarize(text):
    print(f"DEBUG: summarize 입력 텍스트 길이 → {len(text)}")

    if len(text) < 100:
        return "(본문의 텍스트 형식이 다릅니다.) 원문을 직접 확인해주세요."

    try:
        # 한국어/영어 구분 없이 english 토크나이저 사용(konlpy 불필요)
        parser = PlaintextParser.from_string(text, Tokenizer("english"))
        summarizer = LexRankSummarizer()
        sentences = summarizer(parser.document, sentences_count=3)
        result = " ".join(str(s) for s in sentences).strip()

        if len(result) < 15:
            summarizer2 = LsaSummarizer()
            sentences2 = summarizer2(parser.document, sentences_count=3)
            result = " ".join(str(s) for s in sentences2).strip()

        if len(result) < 15:
            return "(본문이 존재하나, 요약 결과가 불충분함)"

        print(f"DEBUG: 요약 결과 길이 → {len(result)}")
        return result

    except Exception as e:
        print(f"ERROR: 요약 중 오류 발생 → {e}")
        return "(요약 중 오류 발생)"

#============================================
# send e-mail
#============================================

def send_email(news):
    report = create_email_content(news)  # 보고서 생성

    smtp = smtplib.SMTP_SSL("smtp.gmail.com", 465)
    smtp.login(EMAIL_SENDER, EMAIL_PASSWORD)

    # DEBUG: Check EMAIL_RECEIVER content just before the loop
    print(f"DEBUG: EMAIL_RECEIVER content before loop in send_email: {EMAIL_RECEIVER}")

    # 수신자 한 명씩 개별 발송
    for receiver in EMAIL_RECEIVER:
        msg = MIMEText(report)

        msg["Subject"] = "디지털L&D센터 NewsLetter Briefing"
        msg["From"] = EMAIL_SENDER
        msg["To"] = receiver  # 한 명씩 설정

        # DEBUG: Check recipient for each email attempt
        print(f"DEBUG: Attempting to send email to: {receiver}")
        smtp.send_message(msg, to_addrs=[receiver])

    smtp.quit()

# =========================================
# 이메일 내용 생성
# =========================================

def create_email_content(news):

    body="디지털L&D센터 NewsLetter Briefing\n\n"

    body+="[주요 뉴스 TOP20]\n\n"

    for n in news[:20]:

        body+=f"""
[{n['tag']}] {n['title']}
요약: {n.get('summary', '요약 없음')}
출처: {n['source']}
중요도: {n['importance']}
링크: {n['link']}

"""

    return body

#============================================
# dashboard(creat HTML)
#============================================

def create_html(news,chart_file):

    tags=sorted(list(set([n["tag"] for n in news])))

    html=f"""
<!DOCTYPE html>
<html>
<head>

<meta charset="utf-8">

<title>(AUTO BOT)디지털L&D센터 IT NEWS UPDATER</title>

<style>

body {{
font-family: Arial;
background:#fff7f2;
padding:20px;
}}

.container {{
max-width:1000px;
margin:auto;
}}

h1 {{
color:#F37321;
text-align:center;
}}

.search {{
width:100%;
padding:10px;
margin-bottom:10px;
}}

.filter button {{
margin:3px;
padding:6px 10px;
border:none;
background:#eee;
cursor:pointer;
}}

.filter button:hover {{
background:#F37321;
color:white;
}}

.card {{
background:white;
padding:15px;
margin-bottom:10px;
border-left:5px solid #F37321;
box-shadow:0 2px 5px rgba(0,0,0,0.1);
}}

.tag {{
display:inline-block;
background:#F37321;
color:white;
font-size:11px;
padding:3px 7px;
border-radius:4px;
margin-bottom:5px;
}}

.importance {{
font-size:12px;
color:#F37321;
}}

</style>

</head>

<body>

<div class="container">

<h1>(AUTO BOT)디지털L&D센터 IT NEWS UPDATER</h1>

<p>총 {len(news)}개 뉴스</p>

<p style="text-align: right;">`26.3. ver1.0<BR>made by Digital L&D Center 이승훈</p>

<h2>뉴스 트렌드 분석</h2>

<img src="{chart_file}" width="400">

<input id="searchBox" class="search" placeholder="뉴스 검색">

<div class="filter">

<button onclick="filterTag('all')">전체</button>
"""

    for t in tags:
        html+=f"<button onclick='filterTag(\"{t}\")'>{t}</button>" # Corrected HTML attribute quoting

    html+="</div>"

    for n in news:

        html+=f"""

<div class="card" data-tag="{n['tag']}">

<div class="tag">{n['tag']}</div>

<h3>
<a href="{n['link']}" target="_blank">
{n['title']}
</a>
</h3>

<div class="importance">
중요도 ⭐ {n['importance']}
</div>

<p>{n.get('summary','')}</p>

<p>{n['source']} | {n['published_date']}</p>

</div>

"""

    html+="""

</div>

<script>

const searchBox=document.getElementById("searchBox")

searchBox.addEventListener("keyup",function(){

let keyword=this.value.toLowerCase()

let cards=document.querySelectorAll(".card")

cards.forEach(card=>{

let text=card.innerText.toLowerCase()

card.style.display=text.includes(keyword)?"block":"none"

})

})

function filterTag(tag){

let cards=document.querySelectorAll(".card")

cards.forEach(card=>{

if(tag=="all"){
card.style.display="block"
}

else if(card.dataset.tag==tag){
card.style.display="block"
}

else{
card.style.display="none"
}

})

}

</script>

</body>
</html>

"""

    return html

import requests

session = requests.Session() # Create a session object

google=get_google_news()
# naver=get_naver_news() # Removed Naver news collection

articles=google # Now only uses Google news

articles=remove_duplicates(articles)

news=[]

for a in articles[:30]:
    print(f"DEBUG: Processing article: {a['link']}") # Added debug print
    text=get_article(a["link"], session=session) # Pass the session to get_article
    print(f"DEBUG: Article text length after get_article for {a['link']}: {len(text)}") # Added debug print

    if not text.strip() or len(text.strip()) < 100: # Explicit length check before calling summarize
        summary = "(요약 없음 - 본문 추출 실패)"
        print(f"DEBUG: Skipping summarization due to insufficient text (length: {len(text)}), using placeholder for: {a['link']}") # Added debug print
    else:
        summary=summarize(text)

    a["summary"]=summary

    news.append(a)

# 뉴스 기사들 태그 + 중요도 계산.
enriched_news = enrich_news(news);

# 뉴스 트렌드 차트 생성.
chart_file = generate_trend_chart(enriched_news);

# create_html 함수에 chart_file 인자를 전달하고 반환값을 파일로 저장.
html_content = create_html(enriched_news, chart_file);

# news_board.html 파일로 저장.
with open("news_board.html","w",encoding="utf-8") as f:
    f.write(html_content);

print(f"DEBUG: Number of articles to be sent in email: {len(enriched_news)}")
send_email(enriched_news);

print("뉴스 브리핑 완료")

#============================================
# Display news_board.html content
#============================================
with open("news_board.html", "r", encoding="utf-8") as f:
    html_content = f.read()

# =========================================
# check
# =========================================

import os
if 'news_board.html' in os.listdir('.'):
    print('news_board.html 파일이 존재합니다.')
else:
    print('news_board.html 파일이 존재하지 않습니다.')

#============================================
# Display collected news articles 2
#============================================

print('--- News Articles Summary ---')
for i, article in enumerate(news):
    print(f"Article {i+1}:")
    print(f"  Title: {article['title']}")
    print(f"  Link: {article['link']}")
    print(f"  Source: {article['source']}")
    print(f"  Published Date: {article['published_date']}")
    print(f"  Summary: {article['summary']}")
    print("\n")

# 진단 코드(단독 실행)
session = requests.Session()
test_articles = get_google_news()[:3]

for a in test_articles:
    print("=" * 60)
    print(f"제목: {a['title']}")
    print(f"URL: {a['link']}")
    text = get_article(a["link"], session=session)
    print(f"본문 길이: {len(text)}")
    print(f"본문 앞 200자: {repr(text[:200])}")

    # ✅ 요약 호출 추가
    summary = summarize(text)
    print(f"요약 결과: {summary}")
    print()
