name: News Bot

on:
  schedule:
    - cron: '0 0 * * *'  # 한국시간 오전 9시
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 가져오기
        uses: actions/checkout@v3

      - name: Python 설치
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 라이브러리 설치
        run: |
          pip install feedparser newspaper3k lxml_html_clean googlenewsdecoder langdetect sumy matplotlib transformers

      - name: 뉴스 봇 실행
        run: python news_bot.py

      - name: 결과 저장
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@github.com"
          git add news_board.html news_trend_chart.png
          git commit -m "update news"
          git push
